version: "3.8"

services:
  backend:
    build: ./backend
    container_name: "fast_api_backend"
    ports:
      - "7860:7860"
    develop:
      watch:
        - path: ./backend
          target: /backend
          action: rebuild
  frontend:
    build: ./frontend
    container_name: "web_ui_frontend"
    ports:
      - "8501:8501"
    develop:
      watch:
        - path: ./frontend
          target: /frontend
          action: sync
